apiVersion: v1
kind: Secret
metadata:
    name: actual-auto-sync
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    ACTUAL_SERVER_URL: ENC[AES256_GCM,data:9NKiLt0MI+7Hfp2zfWza03Fy0upq,iv:7MFRSG5qezxeTe8ytoaCKVnG2U6kNK6pGVWHXS9LGDc=,tag:7lIhflZ3NyixgoReBYBSqQ==,type:str]
    ACTUAL_SERVER_PASSWORD: ENC[AES256_GCM,data:ztTm6ib4AnTUHpGPwQ==,iv:EKRsfGJtV9lltlHPQkNXmdeo7/WMvCqSV9GdD+FWFzc=,tag:w9EJqRLKG0ZNGz/X71Ay4g==,type:str]
    ACTUAL_BUDGET_SYNC_IDS: ENC[AES256_GCM,data:egMlx1m796kfePGLvFIb7Yp8tg6zogzal50LrfhVq471CWLI,iv:T0CNGz+9xQEgBnaMvFqmlr9ts177w+gbZxuAEKEXlrU=,tag:j9fXGb5nnuuCWPo8TphP+g==,type:str]
    ENCRYPTION_PASSWORDS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S2NFV0NZTVl4R3ExWkpr
            YTFrZlpyQ3EzRVNFZk1oWkh1MS9pdWcrWWc0Ckg2K1p5d3J1TVJLMGkvb0FZY1dO
            OVhiSUZSNk5XWlZYbHBTLzFPd0tnT0EKLS0tIEFCOENpV01teXdUSFROSk5yTmkx
            QUhLMlhnNGFWU2xXZXZjb0Vzb1lEencKfMC90Da4EiiXYAfczCygFds5sEFXvijE
            1v2F9txaoFSaHZlR2/PUFr52P9zCXr5tT5m70rGD2AHI+VCwjcNnIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T14:59:01Z"
    mac: ENC[AES256_GCM,data:rd6VdBCP0Drj/URo3FeN3uRtC4booZRSBg5JdvPGFVgRZ1p186F0ixjKQeTpmuPyx6S1vWkwaxrQM13Rr6RUPDcyR+UcBL6oo7CE1YA0ZzMS5fWIAjCuT1/5GxhVAcJuWzC/L3M5gdh/Rlxu2ur8YeXGtW2Gm3wYDts3z36/yGo=,iv:06GXGYO1uQK967mjMPyz9MKd2YSXPx2jlQRHiX5zv64=,tag:4Bu9KcnpQLSLYmVNQFsUmA==,type:str]
    pgp:
        - created_at: "2026-07-22T14:59:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdArp4P9oyucWT/DlqioEOSWTv843ootKCXB7HEK1iVdnIw
            XbhinCSH8UB2/eTegPIUwXk7wYcZae8+lEI7fQc+YUfPfhygxEKYDa/Aabegzdw+
            0l4BKALYyIRqSRALXfTQdCKgDdzP12CaliXvjJbeoifRcLqGIUbbXkqA28KvOzhm
            G8hGpNq3G6v8RyiajP7N10FhK3wbtJjiWe6YFjncGnlxO2DFuxbPEZv0eK3vPAl0
            =xde0
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
