apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actual
  namespace: apps
spec:
  serviceName: actual
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      enableServiceLinks: false # https://github.com/actualbudget/actual/issues/4920#issuecomment-2858039347
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: actual
          image: docker.io/actualbudget/actual-server:latest-alpine@sha256:1c14eef351234f4b5dd0433865b5de89d70bdbdc57368d5b07e910662c6498f9
          ports:
            - containerPort: 5006
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: actual-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - node
                - src/scripts/health-check.js
          readinessProbe:
            exec:
              command:
                - node
                - src/scripts/health-check.js
        - name: sync
          image: docker.io/seriouslag/actual-auto-sync:latest@sha256:23e89abba5dbc7404750aa1f95d52bd910df7157d2dc45ad934604540b6623c9
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: actual-auto-sync
          env:
            - name: CRON_SCHEDULE
              value: "0 1 * * *"
            - name: TIMEZONE
              value: "America/New_York"
            - name: LOG_LEVEL
              value: "info"
            - name: RUN_ON_START
              value: "false"
            - name: SKIP_FAILED_ACCOUNTS
              value: "false"
          livenessProbe:
            exec:
              command:
                - node
                - -e
                - process.exit(0)
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - node
                - -e
                - process.exit(0)
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: sync-data
              mountPath: /data
      volumes:
        - name: sync-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: actual-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
