checks:
  addAllBuiltIn: true
  exclude:
    # Ignore missing resource requests/limits for now
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    # Come back to these later
    - "default-service-account"
    - "non-isolated-pod"
    # Ignore
    - "dnsconfig-options"
    - "minimum-three-replicas" # We use 1 replica for ReadWriteOnce volumes
    - "no-node-affinity" # Pods can go anywhere
    - "required-annotation-email" # It's just me
    - "required-label-owner" # Myself and I
