apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN: ENC[AES256_GCM,data:z5loiSc2NnoJO+pBgN/yJmUV6Dmfy2kqbnFmjiATqCU=,iv:luF56UZBCx8Q03Vy55Igym1BxiXk7u2wMdePEQIDVjM=,tag:I2SK0LOLDesJFdIjqFRB+g==,type:str]
    HOMEPAGE_VAR_PROWLARR: ENC[AES256_GCM,data:bc/MXtl18ZuuViEb8kc5u0tBczhfcT+uNwvn4kcI0Aw=,iv:gdnq28Iu7VfhBmKHwLGD5HVo3VBtx27eKFKNLLJAS1Y=,tag:SQjB5CZ27Uj+JUsubWLg6A==,type:str]
    HOMEPAGE_VAR_SONARR: ENC[AES256_GCM,data:+cuMPub56/xHzyOkJuhdKam14bg2LS5nidRnJ+Dknls=,iv:Dcr6APOXZOonIU9W/fQmFVDzIyNHbum1i6823/VK0AE=,tag:ix1b90wQvpnwRev7u6PfYg==,type:str]
    HOMEPAGE_VAR_RADARR: ENC[AES256_GCM,data:p7wWdlzLdOKaug+TMGGPVWyJX3i0CxMUorjtgdSbJbY=,iv:rDb1fFvplJTFrvqQYE18RVmSmqVM4jdVNJO9pLxzst4=,tag:rTbFmBBrn/oVMKk8ITSj7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbzFNek5wOWVqZkh5OGlZ
            K3R5djlvOW1NU241UWlhQ1dJTW1BenBFVDI0Cm9VL3VqZVhXR3pWd0xDTVdCWENk
            eTVCeG9TZHc2Mm1tdTlCMDdPOFgwcVEKLS0tIGlFV3BBRjg2Mk13LzRqNjdERkYx
            UDJ0THQ4c0E3T2FqWG9MYVlDKy8vMkEKkejoU4OIW1puGtfUkrISO145VH7GFYfw
            j13SzPY4Dle5m1PgPmFS/ugniF6soJoItiYm6sNsDBGmprHVcni1Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T16:03:50Z"
    mac: ENC[AES256_GCM,data:hVzY40yjcxBuPFzL9mfBeZan4I+QWaUBXN/dlsJoeuReDNvU0ALYuKstLVwVIzNc1d4XAIAUZNGMsoI0UU5yGeQG3f0bPEAp0lJyUEQbQqxVI42Zl2BggZHllH2id1GjffQg/n+ea0uySfsBll+iwtkM1SEh/oFL2Be9ESaY0f0=,iv:Llhe62fESFWO2filAge4Y+0Nl7L9k1GyCSaqDHkaiiM=,tag:2GkiYFI6ND0XRsaiE2eG4g==,type:str]
    pgp:
        - created_at: "2026-05-23T16:03:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAWgxG4MRHJxJ860v6YxATwRt+rnF3dgd1QrHI6m2//iow
            kj0iqjPRRvTgaeaAE32+CoSEabibT3M+fweKqq7QOwV+ACDOgrPQV5eZazB2Egxf
            0l4BurMxksrnNptEv88A6TPtjLgIPMva/OdW4ApuQ00rqw266ZJ26qXAbCe3D42o
            xdcK+ES4Aq4fHwrokbsitT0w+lHj3/QkrZfg/1J6ez3O0+SiNmGgkNS7ZeszH0ZA
            =yi5E
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
