apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:numn8/Y2KK097AGAnbcS/K8CuAmFD3koCpVmz4CSQ4bYQfymMIJIq+mNDV52G0NPEyHeopPOOs068L8CuoStYsKyhH5LDcczuZ1uKJCK6Fx28NbF6wQqE05hkJRcgrEp6/6h+T/tpKA/46wtZnMKao/z2Mgmy6rFLA==,iv:UH1gjGm5WaxXiD5+1TM7zlLqJKEPj+jTu2tjTvA6eww=,tag:hpkix46QoBQ/5W+m/BVakg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dHJqeC83b0tGc1lzZE9h
            RUxkQ05uZlEzSVFza3JSaStJOHVmM043cFU0Cm05Z01CcU0wWmFiK0V3Z3FtLzZp
            TVVVdGMvVjR2T1ppN2RTdnBzL2dpUnMKLS0tIEpGZkdIK0tDUTJDOHE1cEU0YjlJ
            STVPRGFldERqLzJmdEhoQXJvSlNoR00KDuIXUXIaGHDLtBRRVDkqGtT7QRoT6daf
            YavJgcHWWe4JzxEzkQtcVRPefzIk+Zci1AcTdFiC/X3XEJQY7zAEuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:49:44Z"
    mac: ENC[AES256_GCM,data:FYsTNGH+maqp4+66dbcT5LSMf4wD60iAflWExW0rAEj4CbgQdR8oWExnFC+g7Ob8NB/Nn7kyUpv/aEGCFofkAWnAsi3P9TZrc0TbF6/eBgy5TzO4/D9khPKQiwG2+JTmWMr1b9xtlkmgkKI+rjdT9Oxv3KZrDDEziGAI7Cvo7Ks=,iv:LNiyrut0eonWnUC6XFPA7XBrkzZ9PmveX2yzB5OEGUo=,tag:dmkJfUBZnIEIr7F4FRPR0g==,type:str]
    pgp:
        - created_at: "2026-04-26T17:49:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdATeiSJD6WJCnThhxZTXRFjCR6wirVmPnmWSvQk/nyEXEw
            yRns4QGiHDr/KsMUxtIGtv4VCy/9n85T8WXTGE7CqNyRG6YJrSjSTk79CJShd5mE
            0l4Bh6yNf5eeKgRrvGXSd8KOTvpSKftbgQl60zBuqxVylIfRbDfGZ6OkH5PQ3J9P
            DT+jqR7IFpcCPSNZp4YAcSVjztueqraEbBTkzHqn/IRiXz0AQz8v7LDOxjBXnBQC
            =5j+s
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
