apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-postgres
  namespace: apps
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 8Gi
    storageClass: "longhorn-strict-local"

  bootstrap:
    initdb:
      database: umami
      owner: umami
      secret:
        name: umami-postgres-credentials
