apiVersion: v1
kind: Secret
metadata:
    name: umami-postgres-credentials
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:TF8W+aI=,iv:FyEAvCvEYqAVsXHoPgZozzfx3OP+5/v6jba09qfL9jM=,tag:OK9ulNu6QFnYPekAW6Yepg==,type:str]
    password: ENC[AES256_GCM,data:gfptgWrwPip60hKbF3XkeBRQ1Ug1CecGqM4W/ZskXQjpuV9BB5jgq4oIPCtRhqnAQ8c=,iv:q9EmLiEyEjV1g5c8FkvFOoH/dBKQkZ92LGpetlLswzc=,tag:Uzxl+wtcdppU0qMszFySdA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYXNteXg5Wld4WW5mbXBD
            MDhiN0dEcEZrdXVZYThMSGxjUHJSZWdZNURvCmF0SjZFS1lqdXpZUm85RGEzR2hr
            WEFkUGFwWVFFcm0zTUt5MXIyQU1WanMKLS0tIDRTKzhvQ2NPV0RnR2owK3l6NS9B
            VjVQNFJBSmlpY1hCNnFidENGcWpaZUUKrvow0BHIO8co9NRCZ9ILpyJOMGWLUzaJ
            6k6CZU5KwUrMUY/9RG4UpCkAaBP0g9H7BaeFXN8Fq/2VK+8Ez7/1lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T15:00:04Z"
    mac: ENC[AES256_GCM,data:f7NxslHfs+EccHLUBRqScmwoKMDBdSFA2wHyEDXcWL704Dt0FYplptVBWg8jsSt8SFzsDWnJTWhGyl7W/lrzMlwpHUUaei7bVfbfNL5ZSPLKnNTLt0DO8LU+yuSSdxa6Ydec8/dK8NjQtpm6NJyDDDDnEP/qvfCFehKBYXQ9Uhg=,iv:aQgNYZoi9weScN3Pn5pdPTW0P2wQ42l7DN5kmBuUe6g=,tag:GB5KfXU5kM04ciuMMb+FpA==,type:str]
    pgp:
        - created_at: "2026-03-06T15:00:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA2HUOlih9mVkDyhsI46B56iwA+OCGY4Bj0xCmMo9fRzgw
            oGCNDzDtzHwlHIv6cnqycBwLJrlTMsjRlf/+B/a9Wb4qyPS1E7S+bBeuadjvwZip
            0l4Bi72G389L69bkqm7Zw8Vp61Dgkd3z6o6vT0NmeSRrIP8VYt1Vc9NPdgrRPdHu
            pIscKOLNfuXw2AKRtDXmFP/n/vfnj5ZIROqzloRew3sNpBsPLXgO+SsmouYO75/7
            =uhCB
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: umami-db-url
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:W3sR0RpqhyCWtI3oRbIM1qU02k26qD2eoPSF5MU7Vr0QGEKKy0XJpFUCVStmu187c9zgJ4Uf6x8/dqMVCBh54aqLa+ADfvpzFgCMElEhaV3vNaBtdo5iNbVeH1cCJ7G0Mo0rAXwsaYJSAMsje4KI8ZlaU+MOT5ALgA==,iv:8ZUvNfmR0zKmOEfU4S9rQT3RY71yRHUCOAQKSV5YK6g=,tag:Vuzj/za99KHlgcoeCjxHWQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYXNteXg5Wld4WW5mbXBD
            MDhiN0dEcEZrdXVZYThMSGxjUHJSZWdZNURvCmF0SjZFS1lqdXpZUm85RGEzR2hr
            WEFkUGFwWVFFcm0zTUt5MXIyQU1WanMKLS0tIDRTKzhvQ2NPV0RnR2owK3l6NS9B
            VjVQNFJBSmlpY1hCNnFidENGcWpaZUUKrvow0BHIO8co9NRCZ9ILpyJOMGWLUzaJ
            6k6CZU5KwUrMUY/9RG4UpCkAaBP0g9H7BaeFXN8Fq/2VK+8Ez7/1lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T15:00:04Z"
    mac: ENC[AES256_GCM,data:f7NxslHfs+EccHLUBRqScmwoKMDBdSFA2wHyEDXcWL704Dt0FYplptVBWg8jsSt8SFzsDWnJTWhGyl7W/lrzMlwpHUUaei7bVfbfNL5ZSPLKnNTLt0DO8LU+yuSSdxa6Ydec8/dK8NjQtpm6NJyDDDDnEP/qvfCFehKBYXQ9Uhg=,iv:aQgNYZoi9weScN3Pn5pdPTW0P2wQ42l7DN5kmBuUe6g=,tag:GB5KfXU5kM04ciuMMb+FpA==,type:str]
    pgp:
        - created_at: "2026-03-06T15:00:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA2HUOlih9mVkDyhsI46B56iwA+OCGY4Bj0xCmMo9fRzgw
            oGCNDzDtzHwlHIv6cnqycBwLJrlTMsjRlf/+B/a9Wb4qyPS1E7S+bBeuadjvwZip
            0l4Bi72G389L69bkqm7Zw8Vp61Dgkd3z6o6vT0NmeSRrIP8VYt1Vc9NPdgrRPdHu
            pIscKOLNfuXw2AKRtDXmFP/n/vfnj5ZIROqzloRew3sNpBsPLXgO+SsmouYO75/7
            =uhCB
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: umami-app-secret
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:p9FvJtAsyFluqM1Dcn81GZjDCucbHXzcIueDU4G6XuJfOYqnZXoecCX3+R5F6HRdftlpZdyMAHhTyGvqhACUlg==,iv:6qd2sg25cp5LB9ZKRp+8rb6cZDINBcDqLg7J2YqFH50=,tag:2WyEMKw10TRQWvNUAnhsYA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYXNteXg5Wld4WW5mbXBD
            MDhiN0dEcEZrdXVZYThMSGxjUHJSZWdZNURvCmF0SjZFS1lqdXpZUm85RGEzR2hr
            WEFkUGFwWVFFcm0zTUt5MXIyQU1WanMKLS0tIDRTKzhvQ2NPV0RnR2owK3l6NS9B
            VjVQNFJBSmlpY1hCNnFidENGcWpaZUUKrvow0BHIO8co9NRCZ9ILpyJOMGWLUzaJ
            6k6CZU5KwUrMUY/9RG4UpCkAaBP0g9H7BaeFXN8Fq/2VK+8Ez7/1lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T15:00:04Z"
    mac: ENC[AES256_GCM,data:f7NxslHfs+EccHLUBRqScmwoKMDBdSFA2wHyEDXcWL704Dt0FYplptVBWg8jsSt8SFzsDWnJTWhGyl7W/lrzMlwpHUUaei7bVfbfNL5ZSPLKnNTLt0DO8LU+yuSSdxa6Ydec8/dK8NjQtpm6NJyDDDDnEP/qvfCFehKBYXQ9Uhg=,iv:aQgNYZoi9weScN3Pn5pdPTW0P2wQ42l7DN5kmBuUe6g=,tag:GB5KfXU5kM04ciuMMb+FpA==,type:str]
    pgp:
        - created_at: "2026-03-06T15:00:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA2HUOlih9mVkDyhsI46B56iwA+OCGY4Bj0xCmMo9fRzgw
            oGCNDzDtzHwlHIv6cnqycBwLJrlTMsjRlf/+B/a9Wb4qyPS1E7S+bBeuadjvwZip
            0l4Bi72G389L69bkqm7Zw8Vp61Dgkd3z6o6vT0NmeSRrIP8VYt1Vc9NPdgrRPdHu
            pIscKOLNfuXw2AKRtDXmFP/n/vfnj5ZIROqzloRew3sNpBsPLXgO+SsmouYO75/7
            =uhCB
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
