apiVersion: v1
kind: Secret
metadata:
    name: umami-postgres-credentials
    namespace: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:l9d3/Zg=,iv:g5lf3H+idCwj8hK8SB02xHfUjhiOGFowSOu6TNNzdzM=,tag:FuSDIx0DnHqbby1KoLbeag==,type:str]
    password: ENC[AES256_GCM,data:AvuxeDBaAPYe6INPZ3EETVLqpHIpPDbtrfYzlf1r6AE2j4AqSoA8cULBnOtGyDJUnhI=,iv:T0khaP2831G29q7FJh0q7inPFJQFakYGPVHeeA7LP0s=,tag:qIHmPRPj5Tl6ZxSY1srFLg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmFFeGRyajFMMG5TMG9V
            YkJwcmxyTXh4Z1pUYWExekRKVXNEUGx0Q2tBCmU3YUZnZXE2TW1MRCtUYm5PcW5U
            QkYzTHpBdTZUSjhQUHdjSkh3QkcwVlkKLS0tIGpPM3Vqbkp2ck83N1dkN3YzL1M2
            YlRYSHY3UEMzcWcwUHNwK2JpMjRxSU0KY/AygpadlCjFaJLuxthE4HtHFIj/Sc+w
            vGud3v1D5G3/oREhOnw+z52IcIU486zxIVf50rTtSYbNoQigCAd2+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T14:40:21Z"
    mac: ENC[AES256_GCM,data:2chx1QIo2smF1A+VaJ5T6xRLjXvg491oX05C3DMyuY/PJ85oazSm+ElyVt397jimzSfkVFu0UgUBErwgc8mNY0T+USaQq/84IgrEf5+HUxzk3itSYvisd2eeZg+B4+S7wMgPaktMKlSCA1zqUqv7iSrjAteQLHzBfabBb5ob7oE=,iv:dsPHxl9uSb9s9R7c8msqGxMq8cVbdaDralLL9+/j+90=,tag:gk2nywfbkMq7dLN0JqgQ8Q==,type:str]
    pgp:
        - created_at: "2026-03-06T14:40:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAwi9q6c1NkKb7HVNPLf1WIMQzxgL1msMhefO+BYPlaRsw
            k07faRMvddRWCnaKQjZMBcw7Y8D3VJK088MM0/8L7jnRwVDXDgJcn7y1U8cyq4HH
            0l4BdTWL35c5YRzk8Bx1FK20bXvpQh0tT5zHbNskSxbzUHXGGQW8sBiw11Qcpwbe
            lfahFt5HqAtc+KXRSoa1Yjz6DfIgs+I9yh3SEEzpTK8qphNia2TEOwrZ6xwnk+97
            =3rHr
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: umami-db-url
    namespace: apps
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:IHWkPXMVpdPhkzR/+syMRvVZEc0TBNYfsbqABKpjDApSens1MNAOTrNj3+nRrn0XBiwROboO9wpGkV5gtWoYnp7aoITJjXtGmUeOgf9dYoM+oKqiAmyuIoR42AC1sGt1ikpcJidf+fi3jWKrbD54MYhJwpu6OSv5LQ==,iv:Q+nPk0xNkfhRZ5rV+5OAcTjvVtqtRiTm0wB/5tCDgek=,tag:Ujmnczs0BipvfU0lEi+5Mg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmFFeGRyajFMMG5TMG9V
            YkJwcmxyTXh4Z1pUYWExekRKVXNEUGx0Q2tBCmU3YUZnZXE2TW1MRCtUYm5PcW5U
            QkYzTHpBdTZUSjhQUHdjSkh3QkcwVlkKLS0tIGpPM3Vqbkp2ck83N1dkN3YzL1M2
            YlRYSHY3UEMzcWcwUHNwK2JpMjRxSU0KY/AygpadlCjFaJLuxthE4HtHFIj/Sc+w
            vGud3v1D5G3/oREhOnw+z52IcIU486zxIVf50rTtSYbNoQigCAd2+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T14:40:21Z"
    mac: ENC[AES256_GCM,data:2chx1QIo2smF1A+VaJ5T6xRLjXvg491oX05C3DMyuY/PJ85oazSm+ElyVt397jimzSfkVFu0UgUBErwgc8mNY0T+USaQq/84IgrEf5+HUxzk3itSYvisd2eeZg+B4+S7wMgPaktMKlSCA1zqUqv7iSrjAteQLHzBfabBb5ob7oE=,iv:dsPHxl9uSb9s9R7c8msqGxMq8cVbdaDralLL9+/j+90=,tag:gk2nywfbkMq7dLN0JqgQ8Q==,type:str]
    pgp:
        - created_at: "2026-03-06T14:40:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAwi9q6c1NkKb7HVNPLf1WIMQzxgL1msMhefO+BYPlaRsw
            k07faRMvddRWCnaKQjZMBcw7Y8D3VJK088MM0/8L7jnRwVDXDgJcn7y1U8cyq4HH
            0l4BdTWL35c5YRzk8Bx1FK20bXvpQh0tT5zHbNskSxbzUHXGGQW8sBiw11Qcpwbe
            lfahFt5HqAtc+KXRSoa1Yjz6DfIgs+I9yh3SEEzpTK8qphNia2TEOwrZ6xwnk+97
            =3rHr
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: umami-app-secret
    namespace: apps
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:Srp0Q1gIGD4MvzznvxqMHMIp7MqWedK6EXDFKQf/WCpvgFwiw5Cn+MiTMxs83JtfIWfSJdPSN379/zkaCzkyTQ==,iv:8esjtGI8YAOHqZn2v0pGuhKxFE3lFuQefd8NYVi7W44=,tag:Zwmu+ddpGy1QEHm/a6IEpg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmFFeGRyajFMMG5TMG9V
            YkJwcmxyTXh4Z1pUYWExekRKVXNEUGx0Q2tBCmU3YUZnZXE2TW1MRCtUYm5PcW5U
            QkYzTHpBdTZUSjhQUHdjSkh3QkcwVlkKLS0tIGpPM3Vqbkp2ck83N1dkN3YzL1M2
            YlRYSHY3UEMzcWcwUHNwK2JpMjRxSU0KY/AygpadlCjFaJLuxthE4HtHFIj/Sc+w
            vGud3v1D5G3/oREhOnw+z52IcIU486zxIVf50rTtSYbNoQigCAd2+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T14:40:21Z"
    mac: ENC[AES256_GCM,data:2chx1QIo2smF1A+VaJ5T6xRLjXvg491oX05C3DMyuY/PJ85oazSm+ElyVt397jimzSfkVFu0UgUBErwgc8mNY0T+USaQq/84IgrEf5+HUxzk3itSYvisd2eeZg+B4+S7wMgPaktMKlSCA1zqUqv7iSrjAteQLHzBfabBb5ob7oE=,iv:dsPHxl9uSb9s9R7c8msqGxMq8cVbdaDralLL9+/j+90=,tag:gk2nywfbkMq7dLN0JqgQ8Q==,type:str]
    pgp:
        - created_at: "2026-03-06T14:40:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAwi9q6c1NkKb7HVNPLf1WIMQzxgL1msMhefO+BYPlaRsw
            k07faRMvddRWCnaKQjZMBcw7Y8D3VJK088MM0/8L7jnRwVDXDgJcn7y1U8cyq4HH
            0l4BdTWL35c5YRzk8Bx1FK20bXvpQh0tT5zHbNskSxbzUHXGGQW8sBiw11Qcpwbe
            lfahFt5HqAtc+KXRSoa1Yjz6DfIgs+I9yh3SEEzpTK8qphNia2TEOwrZ6xwnk+97
            =3rHr
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
