apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr-helm
  namespace: system-upgrade
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts/tuppr
  ref:
    # renovate: datasource=docker depName=ghcr.io/home-operations/charts/tuppr
    tag: 0.4.1
    digest: sha256:a3333bf36964e1d08afc50c9bb111a71193b0f49309012046d863c024d0f5ebc
