apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr-helm
  namespace: system-upgrade
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts/tuppr
  ref:
    # renovate: datasource=docker depName=ghcr.io/home-operations/charts/tuppr
    tag: 0.5.4
    digest: sha256:7152c0ba3dbf72999099a2fa4b41ad3e498c63d6e6ec9c62abb36ff04c2f62ef
