apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-app-secret
    namespace: sparkyfitness
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    api_encryption_key: ENC[AES256_GCM,data:f8g45fofzCT1j8QaMZAyzGwlD7SKljuWbnKvmUgxuvfHwmTebXylL5YqJLN+crcqsys+XB+nXla9/AEbygjaGw==,iv:K0Z+wGgFUm/hNwnIS3FSAatPJIgowWcGrr0f7C8I4iQ=,tag:Ke91K3h1avI5oFNBQTefyQ==,type:str]
    better_auth_secret: ENC[AES256_GCM,data:KaDXx5YmGRViGvz0G/VhvGDRTXiLYHXAl8MCfdsEpBsuu8LzrLrZaR3uz9ueFs/mwAc=,iv:dNawmvqNut0km4TgaWuicrINeGtR3Unfi5Zsxtc4j/8=,tag:fZDUfzktoomjmqJAAqItMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUx0WStUTjJwWElQZW1Y
            RnZnL3cwR3hWMWhlemNqbzlJRVpHT1RsdVFVCldFWDcraUZKc05hckNXSlhESVVk
            NzlVVHNkNmRORTlGcE0ySFB2cnRjOU0KLS0tIGpoMG8zOVNKMjBZUm5OL3lodkNz
            RVZrcTFOamgzWkg0MkV5M1g1K3FvMUkKYRXvBzAj2vbSK6qPfc0bVlAICDcOnaNH
            4oT2CUWztdyq78zdRjXJIkUGhOj9om2VAkxoN4Qmr1JjWQoAaSiT3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T15:25:52Z"
    mac: ENC[AES256_GCM,data:YjUfIB0RIzQwSWsk3hT0cUdB1EDCwn0EX8x1j8BB4ly+ClaBpPxO8lRTKj9dbr2uTZrwLfaO3bgzXY2oRnMMCvcxDhd6IGuT4GkK459ChK+Bz++L0DKa3uOCVpDsK6VWmmwgf1GszNTaneREs8wPyeq33YJHdIHY33bxES2+xz8=,iv:X/FzOkoD1OiPOhEJkyJfSQkCDPvsv9RvHJHNh2eYX+8=,tag:ZbRitKPLhenJ17s+SpprLw==,type:str]
    pgp:
        - created_at: "2026-05-18T15:25:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAICcZOsNRVr+Dlq0lx6KdT8SYINOR/g+NQxBKEwgWJHAw
            CG2cs1KfRxyHKRMMpWIwVhKeB6FuYUCkEZFrDLtufxuHedYMxFCo/vW5bkf2gkng
            0l4BQUyfvNzr4YnKc6ErBDmruEGQVXZhZXPBCX0aiZbv+Hl9kX8fY0nqKrXtADPR
            34NFR/9ieVbqg/CHWL4xpBl4uIaQVa8cj4AF2+tuzZrKhaO74bTgrmtD7m7mytZ9
            =BQ9z
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-owner-secret
    namespace: sparkyfitness
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:zdmRb+0D3xq9Bz4=,iv:2KgWGvgItNCzj0LjUdlhfvIa0nbpiZ6PPkHPJhM53d0=,tag:AeghBMxYepwIVgofZITALg==,type:str]
    password: ENC[AES256_GCM,data:SAiOxC2xxauxzgBn30ETVrxbStx9CtVYFd0GLRdB8ZuJiaQBoghl2IOltTNA4kO1huQ=,iv:S5kkugl+BjIiY9ZWqymOT7sD7KIARRWfXD9T6o7tnVY=,tag:yb2QQFauHjNxYit8QYxIwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUx0WStUTjJwWElQZW1Y
            RnZnL3cwR3hWMWhlemNqbzlJRVpHT1RsdVFVCldFWDcraUZKc05hckNXSlhESVVk
            NzlVVHNkNmRORTlGcE0ySFB2cnRjOU0KLS0tIGpoMG8zOVNKMjBZUm5OL3lodkNz
            RVZrcTFOamgzWkg0MkV5M1g1K3FvMUkKYRXvBzAj2vbSK6qPfc0bVlAICDcOnaNH
            4oT2CUWztdyq78zdRjXJIkUGhOj9om2VAkxoN4Qmr1JjWQoAaSiT3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T15:25:52Z"
    mac: ENC[AES256_GCM,data:YjUfIB0RIzQwSWsk3hT0cUdB1EDCwn0EX8x1j8BB4ly+ClaBpPxO8lRTKj9dbr2uTZrwLfaO3bgzXY2oRnMMCvcxDhd6IGuT4GkK459ChK+Bz++L0DKa3uOCVpDsK6VWmmwgf1GszNTaneREs8wPyeq33YJHdIHY33bxES2+xz8=,iv:X/FzOkoD1OiPOhEJkyJfSQkCDPvsv9RvHJHNh2eYX+8=,tag:ZbRitKPLhenJ17s+SpprLw==,type:str]
    pgp:
        - created_at: "2026-05-18T15:25:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAICcZOsNRVr+Dlq0lx6KdT8SYINOR/g+NQxBKEwgWJHAw
            CG2cs1KfRxyHKRMMpWIwVhKeB6FuYUCkEZFrDLtufxuHedYMxFCo/vW5bkf2gkng
            0l4BQUyfvNzr4YnKc6ErBDmruEGQVXZhZXPBCX0aiZbv+Hl9kX8fY0nqKrXtADPR
            34NFR/9ieVbqg/CHWL4xpBl4uIaQVa8cj4AF2+tuzZrKhaO74bTgrmtD7m7mytZ9
            =BQ9z
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-appdb-secret
    namespace: sparkyfitness
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:sLgD6i57IMwN,iv:dFw31GIZOD7GBNdTt3jGEspKAyQZt+8AmqYccpvxS0c=,tag:MsYtlEl7pgG2aS5UWp5yJw==,type:str]
    password: ENC[AES256_GCM,data:iaHIYqk0U/I3oaQY4IeeXadg67nafN8fWuyJOBd7roJ1YtXz2vyNmRbSPABEkyLSrqQ=,iv:eAAAlhtlhNtPgpx6XU12BLJR1VPGcuAPAAJ2M8xefV8=,tag:ZSgXZuU26EgKiDgc9qoZ1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUx0WStUTjJwWElQZW1Y
            RnZnL3cwR3hWMWhlemNqbzlJRVpHT1RsdVFVCldFWDcraUZKc05hckNXSlhESVVk
            NzlVVHNkNmRORTlGcE0ySFB2cnRjOU0KLS0tIGpoMG8zOVNKMjBZUm5OL3lodkNz
            RVZrcTFOamgzWkg0MkV5M1g1K3FvMUkKYRXvBzAj2vbSK6qPfc0bVlAICDcOnaNH
            4oT2CUWztdyq78zdRjXJIkUGhOj9om2VAkxoN4Qmr1JjWQoAaSiT3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T15:25:52Z"
    mac: ENC[AES256_GCM,data:YjUfIB0RIzQwSWsk3hT0cUdB1EDCwn0EX8x1j8BB4ly+ClaBpPxO8lRTKj9dbr2uTZrwLfaO3bgzXY2oRnMMCvcxDhd6IGuT4GkK459ChK+Bz++L0DKa3uOCVpDsK6VWmmwgf1GszNTaneREs8wPyeq33YJHdIHY33bxES2+xz8=,iv:X/FzOkoD1OiPOhEJkyJfSQkCDPvsv9RvHJHNh2eYX+8=,tag:ZbRitKPLhenJ17s+SpprLw==,type:str]
    pgp:
        - created_at: "2026-05-18T15:25:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAICcZOsNRVr+Dlq0lx6KdT8SYINOR/g+NQxBKEwgWJHAw
            CG2cs1KfRxyHKRMMpWIwVhKeB6FuYUCkEZFrDLtufxuHedYMxFCo/vW5bkf2gkng
            0l4BQUyfvNzr4YnKc6ErBDmruEGQVXZhZXPBCX0aiZbv+Hl9kX8fY0nqKrXtADPR
            34NFR/9ieVbqg/CHWL4xpBl4uIaQVa8cj4AF2+tuzZrKhaO74bTgrmtD7m7mytZ9
            =BQ9z
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
