apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-app-secret
    namespace: sparkyfitness
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    api_encryption_key: ENC[AES256_GCM,data:X49YoHL89H23+ZFM9KktYnTrjrALBrJM9kK0De6sjPECR1jFxzOqGn5Vve9doG931fw8Hfv0gbtpMIq/iVbycQ==,iv:O+J/pyz5mwWa29kj6n4pONhDu56QIGpkNUxAbFBN7PE=,tag:eGMrzXBXClK2lbag8UC1PQ==,type:str]
    better_auth_secret: ENC[AES256_GCM,data:usAt8VRiVym7B5cdGOfFCtP2P3bo1yJKPMAAF0YrXynnFwl4aVRWQk+5soYVhc0IidM=,iv:no7yVntWXnG4fWcEInZ+hoHSauCFSKaAxRVVtIkOkog=,tag:ef+6pHqSn108fsLuksaFwQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaVd2Vks2S3Zvb01vSGx2
            dU94VTN0eUdrVVhpUUJvL2diVmVERXYySmpBClJ4Rm9FL281MlpQYTRFOWJUK2JJ
            ZWxyOU95cDJlL1lRQkpJWWRMTkZZa1EKLS0tIHU4UU9PdVhRWnVrWm1wQ0RzRlc5
            V0haenRGTDZ3SEFLUmNJZGY4MkowNjQKjcFtN+3VA1egy5B+ahI5C//17ntCzA1f
            i2TBc6s1dvPNhk9O9/6omfkVCYTNGH/EcE7OnGYKN9asvlCdvkTA6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T01:01:22Z"
    mac: ENC[AES256_GCM,data:MMdf+U4pwqOFCLwLYiX1IxUWQWIncJIl8GdCRZchLa37hy1chhfRKkMRnPHywf93SshCIWOqew47Tw58ra2VVDX50wsu2Ull/3w8Fqa9VlHGHmDI5ivMewXqYnKMvfzV3A7Mv4OwoHw5U71zI4Bm06gKeSqanoAIBQxq7nKcQdI=,iv:nWhT8i12N4Z8/BOsLmzq1ubqfJDnMfPn2pMHPk1gt8Y=,tag:3zmyS4aMKVBj4Vn7jHGncg==,type:str]
    pgp:
        - created_at: "2026-04-26T01:01:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAVtb8Jy1848RnG/fzVTam4aWo6dc47Rifv+NGNpenHWgw
            L8O3kSGTZAV0viE3asmUlem5VGA6xsyvqtcOHiF3i3XxBsDMa6k5u/RZEUpbaMeA
            0l4BbKSgHPN5NxpLRTJStRYhuBSSuyeTRBbjikWIOU5AAkPZaT/fWqrfZmAjqdNd
            hwXJYx5tZrdFQ7B2eQl9nSYmjFo7RIf5MGLjlFTqmbIMEWiWDCCnW2MEJmwjlCCf
            =TGkW
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-owner-secret
    namespace: sparkyfitness
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kgjjcjk8G/59Yv4=,iv:IqjGZuaVi84aogzneY9bggmFBZxKHI7n05Cm5xpEBkI=,tag:D8nU4bq7p0kNPb4wybnQVw==,type:str]
    password: ENC[AES256_GCM,data:/84JFlWHRPb9yWSxIWFupGVjuT6JnLkZUgS+OF8OMJsMz4FwgyeaLqPAfxrsEbWHuh4=,iv:NvWJYm3yO6aNzOsg5f2h+cw7Y1kqjKWO2Fpc9jcBVY0=,tag:oyiAh/Jf4q2vv0PKy8k3uA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaVd2Vks2S3Zvb01vSGx2
            dU94VTN0eUdrVVhpUUJvL2diVmVERXYySmpBClJ4Rm9FL281MlpQYTRFOWJUK2JJ
            ZWxyOU95cDJlL1lRQkpJWWRMTkZZa1EKLS0tIHU4UU9PdVhRWnVrWm1wQ0RzRlc5
            V0haenRGTDZ3SEFLUmNJZGY4MkowNjQKjcFtN+3VA1egy5B+ahI5C//17ntCzA1f
            i2TBc6s1dvPNhk9O9/6omfkVCYTNGH/EcE7OnGYKN9asvlCdvkTA6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T01:01:22Z"
    mac: ENC[AES256_GCM,data:MMdf+U4pwqOFCLwLYiX1IxUWQWIncJIl8GdCRZchLa37hy1chhfRKkMRnPHywf93SshCIWOqew47Tw58ra2VVDX50wsu2Ull/3w8Fqa9VlHGHmDI5ivMewXqYnKMvfzV3A7Mv4OwoHw5U71zI4Bm06gKeSqanoAIBQxq7nKcQdI=,iv:nWhT8i12N4Z8/BOsLmzq1ubqfJDnMfPn2pMHPk1gt8Y=,tag:3zmyS4aMKVBj4Vn7jHGncg==,type:str]
    pgp:
        - created_at: "2026-04-26T01:01:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAVtb8Jy1848RnG/fzVTam4aWo6dc47Rifv+NGNpenHWgw
            L8O3kSGTZAV0viE3asmUlem5VGA6xsyvqtcOHiF3i3XxBsDMa6k5u/RZEUpbaMeA
            0l4BbKSgHPN5NxpLRTJStRYhuBSSuyeTRBbjikWIOU5AAkPZaT/fWqrfZmAjqdNd
            hwXJYx5tZrdFQ7B2eQl9nSYmjFo7RIf5MGLjlFTqmbIMEWiWDCCnW2MEJmwjlCCf
            =TGkW
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-appdb-secret
    namespace: sparkyfitness
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:poRLH7D9YmFw,iv:6R8c10zoR5I2HzsXZExh0JZ9zAs6+8oPiJk9cuE7rTs=,tag:Xjh2HFHHVPjYvqi90Lz9TA==,type:str]
    password: ENC[AES256_GCM,data:zUhwUMgkhkVe/obAkTynlWZD04gMirbyayD0A8O8u/8PyPDpKkWZnSKuOPty0I0HMfo=,iv:4xZFvTjozDjXp9Obe0MJLWU6oo/eeLypqFP33ZUTaTw=,tag:M9GjLpRdhRbwGNQHDQMgGQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaVd2Vks2S3Zvb01vSGx2
            dU94VTN0eUdrVVhpUUJvL2diVmVERXYySmpBClJ4Rm9FL281MlpQYTRFOWJUK2JJ
            ZWxyOU95cDJlL1lRQkpJWWRMTkZZa1EKLS0tIHU4UU9PdVhRWnVrWm1wQ0RzRlc5
            V0haenRGTDZ3SEFLUmNJZGY4MkowNjQKjcFtN+3VA1egy5B+ahI5C//17ntCzA1f
            i2TBc6s1dvPNhk9O9/6omfkVCYTNGH/EcE7OnGYKN9asvlCdvkTA6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T01:01:22Z"
    mac: ENC[AES256_GCM,data:MMdf+U4pwqOFCLwLYiX1IxUWQWIncJIl8GdCRZchLa37hy1chhfRKkMRnPHywf93SshCIWOqew47Tw58ra2VVDX50wsu2Ull/3w8Fqa9VlHGHmDI5ivMewXqYnKMvfzV3A7Mv4OwoHw5U71zI4Bm06gKeSqanoAIBQxq7nKcQdI=,iv:nWhT8i12N4Z8/BOsLmzq1ubqfJDnMfPn2pMHPk1gt8Y=,tag:3zmyS4aMKVBj4Vn7jHGncg==,type:str]
    pgp:
        - created_at: "2026-04-26T01:01:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAVtb8Jy1848RnG/fzVTam4aWo6dc47Rifv+NGNpenHWgw
            L8O3kSGTZAV0viE3asmUlem5VGA6xsyvqtcOHiF3i3XxBsDMa6k5u/RZEUpbaMeA
            0l4BbKSgHPN5NxpLRTJStRYhuBSSuyeTRBbjikWIOU5AAkPZaT/fWqrfZmAjqdNd
            hwXJYx5tZrdFQ7B2eQl9nSYmjFo7RIf5MGLjlFTqmbIMEWiWDCCnW2MEJmwjlCCf
            =TGkW
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
