apiVersion: v1
kind: Secret
metadata:
    name: rsa-secrets
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IPy1RvX1AHWXyAANYcgEUhzL,iv:F0gph6Z4KJScRjZZ/tQWW92SKVYU3v0rSToBID1s/Vw=,tag:HorkP+ZdnKpy/QvPn/haKQ==,type:comment]
    DISCORD_CHANNEL: ENC[AES256_GCM,data:5KmEfT4lxLXP9aeFH+rTDROQLg==,iv:d0L8zFqEPrCGPxfprWu79MBlEeaN1384jXvEkxXoLsY=,tag:uhkxLGvAjgYsXjgu38+faw==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:DCuO90qtxnt+YZBihWz6iTJFeTZnswhhqcDZkpXs+nYLhsPWwVa7ZIweGm+j/uSu+7s2rAuWz3vM3vDhXa83uyGDiXc3iMT6,iv:2tPGUP43zbL/MXrO+/GOaI7QC+Ug4AFzGR3vJy3Efz4=,tag:KRL/wELYgx3Al3XypSbbtA==,type:str]
    #ENC[AES256_GCM,data:9GitVeg=,iv:G78tUImZX3zU6ZDs9c3eG5MqyN/a9mtVblhzhk3oHOM=,tag:HK1nDTPnje3uqMcbH9yCpA==,type:comment]
    BBAE: ENC[AES256_GCM,data:QjpqMhqswXBvF8exZPrefefCSUZjig1BUxRAk2f36scntEmo7nI2HZAC,iv:XQ0uzO76P6Fpen5IkclaDb37d+0Wlrduo3XwJZ6oi0s=,tag:55MTYDGDag16vLEJnhSIAA==,type:str]
    #ENC[AES256_GCM,data:jIr6p3lO,iv:8BCZMp/BhYC428CFqYMHGuZl3YpZW9m/ppZzxQ7TbLg=,tag:TAxL9Z5EB7SY3l4grRUkvA==,type:comment]
    DSPAC: ENC[AES256_GCM,data:hAZ3xpwu7Ly4lgOfVbwa79DPEyT5WOLyPTRauGb+V2JBmKAYum7YJUeQ,iv:7bwzLwxLtakymQcVfEmjS9Npk/TS3eV8g0Or0mcHAdk=,tag:2toiH04Z3o0IMgKX37RL1Q==,type:str]
    #ENC[AES256_GCM,data:MalLPYDblg==,iv:AqkSZlKlU9ZAd800xgwWIr4xrtnro/xFZ4pDEGPliCU=,tag:VKVWa+BL4gDntgA1Rrfn8A==,type:comment]
    FENNEL: ENC[AES256_GCM,data:09mo9L9vzx0Nqe95e6+/mYyMH9b0zgvXZdNWy6bL65ZLPHSDvwr5DWtEhNUhHRrQSSTN7QWgebBxnuivYlZVjLJWN/idJ99eXs5YO98//io8,iv:X+v7wlFg6SR0dvS/KqKmgzDzB6AMWkdwqBAwPeQ/0k0=,tag:Wv/ywiOzVqTmdTXNZiXOtQ==,type:str]
    #ENC[AES256_GCM,data:DnZ8z267/aib,iv:H4a0YIz3n2vBOkquMV8kcv6Mlt5dh18+Okal4mKj670=,tag:vjIyJG6xOuBjly4b4Ptf8g==,type:comment]
    FIDELITY: ENC[AES256_GCM,data:dKWMC0j/hl5QtnNVJn15a0sKmGtnJmrjEUj/df0W6Q==,iv:iflJmSxlxGNJ4IsxQEEBKzIjdd74kvusFxluW7KZz/Q=,tag:VZLyPGDImje9F+nGFdQFIw==,type:str]
    #ENC[AES256_GCM,data:2gC0t18aWQ==,iv:qL+ILzOutJRSbGYD/YYGaiir2CJHVPwiZqcHvVVUJqc=,tag:DjEw6AUSN4fsTs4FOZaTQw==,type:comment]
    PUBLIC_BROKER: ENC[AES256_GCM,data:gyowFdRJSfyrT5w+zgo7uxptTvltKo+3X6uUJ0tbav0=,iv:RSkMz0oOMILT4lNRkEFYVf5tKW1Wnv0SbNaC9tdBL+0=,tag:yD744oH6TFd7mcG2RhrSPQ==,type:str]
    #ENC[AES256_GCM,data:9HzKRtKX/RAVpg==,iv:5IyZ3r6Hhw6psS4GAAxZMVM8mBa03ff2NgOBIWvj6k8=,tag:l0sgwGCbLiaOL8P+BKbfjg==,type:comment]
    ROBINHOOD: ENC[AES256_GCM,data:e1y1xyxUquQIfehzuJwZEmcxpsxgcDV5iSXnTvpWLgnoma4/yePw+MFH5t6MQH1GSKP1ygnl5KGukqhEEQo50Exndt7DX1KDzQ==,iv:CdF8VKIFvx6CF48UIJ2NzdufwF3up3q9qenbTmJlLoA=,tag:ZfQN5rY1o3W6wFCges6u2Q==,type:str]
    #ENC[AES256_GCM,data:89wjx6DHKQ==,iv:5U2xJ8HxYyPo6qh3z5U2bJjZdl/+z2rYbCSCu6U+AfA=,tag:Bl0Pmo8HH/m4oZYD7h3V2Q==,type:comment]
    SCHWAB: ENC[AES256_GCM,data:qOIxMjYnu96f/TFpIrXlwEDwm+BXo8nbdUvsbTl8j7MFToaHP65Yg2wwm6DrhzqyEFmh43ilrNJqZm6Ahv19VQ==,iv:4ONWzh1DtowmXA7cbhxmTnWMTtKJmq3+/SDqwGToFC8=,tag:t25i8GDi9GbF/Gheun08Qw==,type:str]
    SCHWAB_ACCOUNT_NUMBERS: ENC[AES256_GCM,data:38ctQ93JiLw=,iv:spGhtJFXuffOAp8diLOtgFK7X0BAPSjCUuLNcL58QHs=,tag:f/U6eesiKzqE9bCZ3PSYHw==,type:str]
    #ENC[AES256_GCM,data:rdKJr8hm0Yu0JeY=,iv:WsmiXFka3y0vf9G7SbOYpgJu9EIbf9ZtUa93YtIlTEY=,tag:1vpV20t2XFKARZie+x8VKw==,type:comment]
    TASTYTRADE: ENC[AES256_GCM,data:FCYI2NbWv7MO0KmIelH3yIaDTghTvbzShsy3eM2NHUPwuYWsL8Vhz+H9ngnBpkw1yNrhELnEQAIVaQxmKxZco5qBty9eNSN8mmJjtgpHhIhbFHKy8aQoicQnz5ma8c/h5rW/c3I8RlWiTzb80SWS+2rsxihnegZSQJc7LpwiFd7ZrSaKRRskhwMj/iXjqjZ2ZeCPaA26j6sNws6u1BkMz11PzkvBAZx7Tft7UFj/2wxDfB21peZLw2iqKRxkGtKBuvLHMDI/bT29HlzZ5LO1E3SxIWnGSj+HQcEZYsI01v+VW3NOd+SyjuBG7otuTcb0fX5bvdQzkrv5UqWCm0T1o7muh4IgzPnzP1Stux5EK59KTO63CSmxuSMG7GVkaQWgCY5gCRmzttYape1mxL8gorZ0J04Cyv4LpEc6oV+WhHmFS5xdWdes/1iadQK0Mzs8LqxtvcgVX6jQnYCrNOSt9U5zoZY8m9LQOfBrcQvmJBVw7A2PpicMFyFQrXMfyryyXhPQN2RLaNZh1lI6vz7SZJInp2CuoDY8nE88wIbygZVJ2HLVr345v9bOVzXtPFRRWShdEOrh3vOmYka/i6K0j5rZOkUWYV8Lv3YKLjCagzz9hVrMB5ZN6WQMpNCQloIXSJ1s8KDOazjs3jxWDHz9e+RMpPvyyPYHVP3iSBgFDUkFFe0rV10+ePBVgsS2Z9/445fOixs5R4oOFcZXRSFP17hkjaUWEoZcN/0pK+5J3zowRNM=,iv:bhs1PMTlkaypZUy5gjUwAOn3hA2UelzATOsRr/zp518=,tag:+KKvnjRomxXV9u4JOlgkbA==,type:str]
    #ENC[AES256_GCM,data:pe+rokmzpg==,iv:wYBkNqpNstPPh4YcgwZZ8Lth952RTaWX1trxgh3KZJQ=,tag:LCvQ/c14mEHd0kNiYycfGg==,type:comment]
    WEBULL: ENC[AES256_GCM,data:eeuFMMrQSd3iFP0ih9klUyQfaGOLc+a90F9uFYlCMXRh2x2fqrLVzNObYfuNVfJ4yQtmhy8jC+5xnoarg+ye0Wfyu9ME57o8cFdOjGfUC3mmeg==,iv:R0lTeKE/QuxseJzodUMaUtTl8YUWEeJpNtCl9CLcf2k=,tag:dUAVCzl3PwIbmi8UJussXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QlpXRHA0eXBaK2ppM0lU
            UW54NnBhVHlrUGordm4yOGRHYXJHRVZ4ZFFFCmxuU3hFS3RNcjA1ZEQ4NWcrK1o2
            cmpIOUFCbEQyMDByMG9ZYjljNzYwSTAKLS0tIEpDZFplYzN1R1hEYXdmY29IbFRD
            TS84Sytrb1JZbGtyYnhuaXgvWGxHYm8KqdvwW6WqnRNn6wFV43sWao5EZsv9ZFmD
            GkjbPOUUk7WTfXe6zGNUBTW8gobzFb3XeYjtloMt1BwD6Opw0r7CbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T20:50:43Z"
    mac: ENC[AES256_GCM,data:EcKRMiokjGCRjC2em66em1DysgsbKCel1YmCdGs8Ygv51a20JkLpCsl1XHmycBw6nVrXKbF44+8tJ0wdwleeTThKlk1Z+xoBoEzMEnd1hhIz/4Vdxw0/0qvxd0QufUEOru7mOvo942RT3QuFsrky3PlX470Fp6U7pYMKcmG3w28=,iv:uosJxytx9YFrhyfEImgDG3lWuNN50NygyvjRsTLgZT4=,tag:3RhCQhgGXupyTgkmCDU5ZA==,type:str]
    pgp:
        - created_at: "2026-08-09T20:50:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAaJ7e/gpOna+I8RkD3CAvffrCHvcZHcJKyKTxhjd6KiMw
            mCtGGWlG6rxSg8T1jEJsE1Qig+JtKrGvo1fxtPVqfKTiwqKaBM5/3zb9qGGI5Esg
            0l4BrlRLoc2taEs5qjbPISojA2eLUDfQCBnZIJnS4JKDxKTIHkXFkzVTkB6P2ySL
            ojS5/AS/4+FJRSU6avoykC8EALM5P/M62rNg8QsaXKygq//jjZoEDtMuOaS/8ylF
            =xTQK
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.3
