apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.27.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg
      interval: 1m
