apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-cluster.yaml
  - helm-release.yaml
  - helm-repo.yaml
  - namespace.yaml
  - storageclass.yaml
  - postgres-creds.yaml
  - user-creds.yaml
