apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-postgres
  namespace: apps
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 1Gi
    storageClass: "longhorn-strict-local"

  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      secret:
        name: miniflux-postgres-credentials
