apiVersion: v1
kind: Secret
metadata:
    name: miniflux-postgres-credentials
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:lplxC9g5j9o=,iv:YtGGK7L8cgNwSz4rDimgRVr2/KlAm6pgj59UJjk8n1w=,tag:YT3kujSLAri7IXN69LYHCQ==,type:str]
    password: ENC[AES256_GCM,data:92dMSqv4JcGxto7y/G3ScDU2Ey4ySu7uQeKxWb+Ckzsk0DWNUY7N7wrR6K8u8H10UMM=,iv:wIUqtr4BxYNiFdr0jz/RUR2wRT2HJfHHEK8EUWeEdmI=,tag:Ok5JO8nDBRAPlfBRLKNWQw==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYlcreWRhd2NuYWxXZFRo
            c3QyM00zUitxQ21KRlIyQWc5aXkwU2xhREZNClltb2tkUGl3SkpaNnVTNzBQMGtW
            VE9ROW9kN0Vld0Q1M1daY3dJU1E5WXcKLS0tIGRPb2JNWjBhc0JCTDk5WUpCSzlm
            UTQ4c2toRHpnM0dQQm5MNGlOWjNJK2sKLz13Ippt3JmtE25fbmGo/Uw8WR9YJl5i
            +Wpl4BIUA5ZhTKhECpAD6oPY5rBfbGQuBLMv3p5uhgYYri7lCgytHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T23:54:33Z"
    mac: ENC[AES256_GCM,data:Y/XzqNJgFxd0qu8U812w/aKm79tTbI1+Hyk98FlWfRltQoylrf/mrFIn92YJ/4L82WSNjGkwMofgCYVdb1d7h2jzPA+Xu1sK9oMcWIfuh6Z1zF7j1aai2xM2u/RrsrmtqbGwu9tk8LaJ2WXClh0jZSnfefkbvfxlW7DF+uF1hCc=,iv:i3iuD3ySW/QOwMUM7S3YyhNv8GSz4asWPPLefD+pQ00=,tag:TmcpGqM4pNE40/LMciC03A==,type:str]
    pgp:
        - created_at: "2026-04-25T23:54:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAceI1j/LeOJ9/QUjQ6PlFC+uaEsINTTfH2g1Sg3rPzwUw
            WremktzNPU3IhV1aKSZwKph7u7RCxthxjddMRfzfDzXdvqGd/1jN9hB6hCwrsbRg
            0l4BW64KLJmIpTdfYv68epi1mf5yMfmmjTdx7EQ9bJYRyGEdxuJi+AP54uxWqsS9
            qFNnp9JgwP14QxlNGh5qRGlHPuaapVM7/bwmyMwe+ks1mfLHhqjrue/vpZ1LxS/3
            =hgyE
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-env
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:PvsQ0dC7TFQ=,iv:q50K4BmuREK4r+D8EelhKJ+mp6IcxkYQtfd131EJgSA=,tag:Seyzi+GloyfaonubSNBwBQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:yLix8mgl8Ei/h/u3RvCfTZDiW0+Mn+8qp7S9sxgt96tee3oKOsLiNTtI2rXLNiKDLQ0=,iv:N6TYsqteJhNwbruF928MlrfrfdX3HpzcCp2Wqa5gSy4=,tag:K6BRZ7s5jRxp4LCMs0zJfg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vEWszLgjceFVEYeW31tQIgh+vQhENAJeQbkWhGN7Ws2mxzYDvUauE53LUFHWR9NFU7F9dlsUnYf4bKH3P59S5zOIuya88WNvthu9IP9C+G/c8QN1H1y2HhHtA1vATL82bOP/Q0LB1XmPtqFR875tMO8CXPsA/qVfCZaabuQOLHh6gM1BcHn/IyzA,iv:3ZSa0QOVRbWunf1yJIFkoutM22L/Sy0VkD5S3aZ7nG4=,tag:kj7CbzalbrfLl+0DOPyt1g==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:zJyj5ZZrTXb5IhI38wqFuKgtmirBJeAQQUY2cxQ6gH38D/gfO1wEuHM0PGLu97NEMVAsp0ClMWOEATeEQOl+kQ==,iv:0OyN+gjAVu7DS3ko82vyoK0nMO59NU0fFUiu8cOthYY=,tag:9sfdxl9DydPFuYaoTgpbVg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYlcreWRhd2NuYWxXZFRo
            c3QyM00zUitxQ21KRlIyQWc5aXkwU2xhREZNClltb2tkUGl3SkpaNnVTNzBQMGtW
            VE9ROW9kN0Vld0Q1M1daY3dJU1E5WXcKLS0tIGRPb2JNWjBhc0JCTDk5WUpCSzlm
            UTQ4c2toRHpnM0dQQm5MNGlOWjNJK2sKLz13Ippt3JmtE25fbmGo/Uw8WR9YJl5i
            +Wpl4BIUA5ZhTKhECpAD6oPY5rBfbGQuBLMv3p5uhgYYri7lCgytHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T23:54:33Z"
    mac: ENC[AES256_GCM,data:Y/XzqNJgFxd0qu8U812w/aKm79tTbI1+Hyk98FlWfRltQoylrf/mrFIn92YJ/4L82WSNjGkwMofgCYVdb1d7h2jzPA+Xu1sK9oMcWIfuh6Z1zF7j1aai2xM2u/RrsrmtqbGwu9tk8LaJ2WXClh0jZSnfefkbvfxlW7DF+uF1hCc=,iv:i3iuD3ySW/QOwMUM7S3YyhNv8GSz4asWPPLefD+pQ00=,tag:TmcpGqM4pNE40/LMciC03A==,type:str]
    pgp:
        - created_at: "2026-04-25T23:54:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAceI1j/LeOJ9/QUjQ6PlFC+uaEsINTTfH2g1Sg3rPzwUw
            WremktzNPU3IhV1aKSZwKph7u7RCxthxjddMRfzfDzXdvqGd/1jN9hB6hCwrsbRg
            0l4BW64KLJmIpTdfYv68epi1mf5yMfmmjTdx7EQ9bJYRyGEdxuJi+AP54uxWqsS9
            qFNnp9JgwP14QxlNGh5qRGlHPuaapVM7/bwmyMwe+ks1mfLHhqjrue/vpZ1LxS/3
            =hgyE
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
