apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: vpn
spec:
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: torrent-tcp
      port: 6514
      targetPort: 6514
      protocol: TCP
    - name: torrent-udp
      port: 6514
      targetPort: 6514
      protocol: UDP
  type: LoadBalancer
