apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-default
  namespace: metallb-system
spec:
  addresses:
    - 10.0.2.14/32 # Postgres CNPG
    - 10.0.2.23/32 # Jellyseerr
    - 10.0.2.36/32 # Jellyfin
  autoAssign: false
