apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-apps
spec:
  capacity:
    storage: 14Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/Shell/media
    server: 10.0.2.20
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=3
  storageClassName: ""
