apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-apps
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14Ti
  volumeName: media-apps
  storageClassName: ""
