apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 10m
  chart:
    spec:
      chart: mend-renovate-ce
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mend-renovate-ce-ee
        namespace: renovate
  values:
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    renovate:
      existingConfigFile: /usr/src/app/config.js
      extraEnvFrom:
        - secretRef:
          name: renovate-env
    extraVolumes:
      - name: renovate-config
        configMap:
          name: renovate-config
    extraVolumeMounts:
      - name: renovate-config
        mountPath: /usr/src/app/config.js
        subPath: config.json
        readOnly: true
