apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "extends": ["config:best-practices"],
      "labels": ["renovate", "dependencies"],
      "kubernetes": {
        "fileMatch": ["^manifests/.+\\.yaml$"]
      },
      "flux": {
        "fileMatch": ["^manifests/.+\\.yaml$"]
      }
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:41.91.2
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
                  readOnly: true
                - name: work-volume
                  mountPath: /tmp/renovate/
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
