apiVersion: v1
kind: Secret
metadata:
    name: sops-gpg
    namespace: flux-system
type: Opaque
data:
    sops.asc: ENC[AES256_GCM,data:0kn7g5HeMmbra4+No/+MyeiO0YB0OaV6jOQLVmxgtDhpUkzYAE+1+zeDBJfN0pRjhIe5AQFy0L3FvBkZMEL+no/xL2unUpMbRv8M8//Lt9fjuy+Nn3RalaIZ3gciJTLvYHExtZezAPsjNXjVlUzGtPaXMdo6CZpdz2c+H2prySYswnQlJfeyCrg9cO5OLs5O+a1qi/c4mHl6Fu/puMPA6gLplZwcQBTRaln2rIif2YOxweMwSRAV5cKmbJErr3D4FFeTOZd8zoJE9RK9485tH/5e9IkQ10mbqlcDNZ3zRDZccDyfFr9wDj029l1PZ4l3/QTNPWiFbNYlXvGB932y6KKkFKg4vtybv8UfG75Ucib0lRVDv/yINpUQ7aM7Ul/iLpRW7QXXwz8bYTQNewir7mEJJ3a5od6LHmLcBLQLDvQJDxzzoEowiP7xitsz3yZUpR64SKstMRtwTPD0JjDdLv8ULIh0j+z/laziiqIxbdhrpS8EqFX5wrrjHIqstpB8LUMZtD0V/CWSICUYUIaeWLxRuGAQV4Tl9dWZSpBO6frZIImpXr3HSc0Xrw+TtwChXDCTyJP9yJKsfggeu6XV1apHQRSqot7TUSzEQeiskzsTA9xHrovE1HPGEr0Qi9pu/nizlTWppRFaTjP38SUPCBT2fzo6kkisFg0mFGfmDqe5doZc5MRKNj2SCR6e4+fhfIP1+Mh3ZIivU/HEsNyuhFnFxZLZqh5VvpGcKj04yuuN7VnENE/aWNXziwdZOarc1B6ObQknRe6WGI8F3IBCaz+glonFXdidJWrqWbEZxOl2V1bBdBTYa684HiuutruidiQjJa2BqpN1mWAXosFGlo9zFsW3DxX8bZYtzG2vem3ozcHe4ECAYT+Y/z1s99xr4O5MMIedxEAGrgaqKEyVetVZEaQnZxw0wc7QVvvzs/IOwQGl0hHM7wv/bfBbDZKFcntwK6JlCGnxnIpaFRFdppntPzksFiEsrNGa+TTX5Yy/UeRm3Jb/11v5GbSasNFpiO0F24fTT9lAJuBViPR2zv9lzuMaHNB3/x1Rumq8ST1P+QUEc3WT/s9EaGNHHQZe+4gaNh1PxCBUJGFLw3eDRoMnK5/1k6qaLjHg/Z+Jf4uq+4+H7KieKXz8GOOmxXrvekXCFc7kJC8gxFIzcqacABfNPfmAsxPbBy1+uowC2+si0VGuyU0hs/pEuKj9GuInruZxvLFSlJRfUKXs1cf0kVxkOzFXLByFNhGdkAs+LXwnivriQ2pt+u4gYp42kNqWRBPS0HxRrw4tqWDprA==,iv:Mzghg4oQe+wWkDQuC1VyEU4T5pREfy2eE6rUlz294P0=,tag:XHCZLDUrDNpGzZSgGFpy5w==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTU1SMDQwYVVKV2dUb0RR
            V1Z0cFBtYmZvMEVGblQvZEdEbnlUbXpDUEVFCmZ1RmRjQVgybW5mc2lGZDhQQTRO
            dHRjUXdONGFUdmFYRDJ1bUVPellESG8KLS0tIHdpdTl2VGx2K3VZcHN1Yys1cFZh
            bndZZXpLT0VYei9hWVc1Njl4bnFQVTgK1K8ABiuMbxQwXN7n+SRKMQsP/A9wyeaN
            SzKp8qzI3kz/AT+1lZk4Zpsj1jA3QQWXta2HiOe0c3hPAs2uEYFMtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T12:39:01Z"
    mac: ENC[AES256_GCM,data:xD8A2EmjM5v2ENzkrxQ72tR7+QssyyFDUDbUwVRi8bMJMoFva9U3Dli3PVBpsnvLJy+emqL/lB6wwKOX5A/xpXQddUwhA4xVfMnf80XhQqCY3TU0WjZqWTjLoVhSTMmlb+w/kH9lLqu1+yZUNr/jqm6vXoaXtmCwsVgqAEfjFhI=,iv:cx7PEneoF6qJSj83YYpCZuOCXPyhUzCi/w7/uZnF8UM=,tag:0+zxRDDzVZlzUiw+Col3sw==,type:str]
    pgp:
        - created_at: "2025-09-19T12:39:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAA2vMvorIhcVNX06i8NqMZCDyVmNrbHUFvGWuRkZhR28w
            N+svUGGymlrh7BSkD0764piadRPxVD4Nvk5NFRt8QoQlGg6CFeX81zGCnlxRA6Ww
            1GgBCQIQ0FtlSKI8S7zFLbftsBr9+1XjBuOEEBkuMZkHFkthoXYEEWYQtrpWd2+J
            ueZJm0HJJO7YAyAyv6dLNuRB8Bh0JqzWGoSbAAXewkwNKx6e6u+AiCN7lkS+bKvJ
            kLg/3kU/AjJKcw==
            =CmY9
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
