apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/media/prowlarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
