apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infra/renovate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
