apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: warrior
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/apps/warrior
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
