apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-postgres
  namespace: apps
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18

  storage:
    size: 8Gi
    storageClass: "longhorn-strict-local"

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-postgres-credentials
