apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-credentials
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IMAe9IrhEKoe,iv:su+UvMKFhF6iZajHKomtqO6EBz3xASbHGkADnEovri8=,tag:4rjcX58/uXh2Ht3cPP3eWw==,type:str]
    password: ENC[AES256_GCM,data:mppxVVA8hkRjX5hzmB3k4J5g95LbtC/K,iv:L73+08gFm41JEgjHHCPeGGYhvyDf759aAM1OBb2hBSA=,tag:nUKdEXcJM0ctJxtVMsQ4Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVXBiaFNRWnkvcGtTY2pn
            S1NiRjlVSXltdTNaOWFCT3hoUzlkSTFTREdnCkxjaFZxL252Q0ZQRlpaNmdvNGt3
            eTBKK2p6Nnh5TFB0eDBObHhjcFllelUKLS0tIGM2N1B3aTdadU9aQU5xbE52a3hv
            RGRRaVZHRHVWQjBZS0hxNC9kSjlUZTQKSF8Q7k9i+o6Loj1Hy9izpQDs1ilext0+
            WseMGNXF8hkmErOpG6PVMy07YXA7fvoWKKDYZJvVj77Fq4NaUaY5NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T19:23:28Z"
    mac: ENC[AES256_GCM,data:y6pjci805WpcSi2tXiNUGTmNbPrLIg0ETIMJM7fVerLmXzEG+U9sJ6NxFESfKBAJkpHDrZIyy5Qx7V1x52iqyAqBuxHKfWURtDS29Bhmhq7XVbJctOTxW2yx2sEWrUvvsRPSOFqu74uO8YEvUnm639tA+htqWCKMwJoAIzVX1wE=,iv:SvYsa3iGYnTKe8GDQ7UClpzAS2SHiZRcJUr96/xhT3I=,tag:OzYZMID3Ah+2jFiE3+sQrw==,type:str]
    pgp:
        - created_at: "2026-08-01T19:23:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAFeCc8r9jBZZsK6SvPYxgCZlrAm589zuXmteoRu5/4Gsw
            0m2Y/CYkJ0i8gljulFEsNWCO/OHmLcs950VJv30kbLPZGEWVsQqBoCCwsaL6/GJb
            0l4BPrbk9F008T5JOh9I3xX09sOYMjhEc5CkDKlbFKLk0JePgavCyvOTEfXzYxNI
            gsdPzZH30/HCL1oihIEo6AQ1PIW794Y8tyMUYvkbO+b6ii25vZhTE/t28CGT2+3P
            =Vf9U
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-app-secret
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:4An6K/rBssgZ8sd7O9P/3I9uU/YzcLad7k4Zmv5TBmm4+TbUmNrDdsnTZTGAFtqZo7M=,iv:CmxZDcyRWi/upyu0gVKgVSsLZaD0JyIfrbaxjGT7bJU=,tag:JA6b0QNnR/+LB0B7J5vuZA==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:KN/BVQVjDtmS,iv:Tml+QIMWIi0OjCniLCCRmoPsdpQyd8fNDwnqRQtqNao=,tag:CKvFkYUytK7uZTbUl50aqA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:R2eONZclRw0VsH8Ke76zZLYcHWrLQ4Jt,iv:rIQAMP6w08MTzBBrxlN+zzPq52WS0fsLARUvoXJ7cz4=,tag:ouJDzvGBoA9mTm/vJ0LTAw==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:khkBINA=,iv:GdVy6D3kgk9i135CI5jodO4UOHBOf4+hoywaYBjzd8c=,tag:tpIwVMGSmGHERpQEy5PQ0A==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ae/vAJAuRVCU71Xf+EC0j8VgNlFOoAc/,iv:fpkDTZXhks4poWbxi+kdgERpr1WsUwbWIlrs3gXHeiA=,tag:Nwb4yxl+0x8t2bh1rfolNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVXBiaFNRWnkvcGtTY2pn
            S1NiRjlVSXltdTNaOWFCT3hoUzlkSTFTREdnCkxjaFZxL252Q0ZQRlpaNmdvNGt3
            eTBKK2p6Nnh5TFB0eDBObHhjcFllelUKLS0tIGM2N1B3aTdadU9aQU5xbE52a3hv
            RGRRaVZHRHVWQjBZS0hxNC9kSjlUZTQKSF8Q7k9i+o6Loj1Hy9izpQDs1ilext0+
            WseMGNXF8hkmErOpG6PVMy07YXA7fvoWKKDYZJvVj77Fq4NaUaY5NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T19:23:28Z"
    mac: ENC[AES256_GCM,data:y6pjci805WpcSi2tXiNUGTmNbPrLIg0ETIMJM7fVerLmXzEG+U9sJ6NxFESfKBAJkpHDrZIyy5Qx7V1x52iqyAqBuxHKfWURtDS29Bhmhq7XVbJctOTxW2yx2sEWrUvvsRPSOFqu74uO8YEvUnm639tA+htqWCKMwJoAIzVX1wE=,iv:SvYsa3iGYnTKe8GDQ7UClpzAS2SHiZRcJUr96/xhT3I=,tag:OzYZMID3Ah+2jFiE3+sQrw==,type:str]
    pgp:
        - created_at: "2026-08-01T19:23:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAFeCc8r9jBZZsK6SvPYxgCZlrAm589zuXmteoRu5/4Gsw
            0m2Y/CYkJ0i8gljulFEsNWCO/OHmLcs950VJv30kbLPZGEWVsQqBoCCwsaL6/GJb
            0l4BPrbk9F008T5JOh9I3xX09sOYMjhEc5CkDKlbFKLk0JePgavCyvOTEfXzYxNI
            gsdPzZH30/HCL1oihIEo6AQ1PIW794Y8tyMUYvkbO+b6ii25vZhTE/t28CGT2+3P
            =Vf9U
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
