apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-config
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:TlIWqUo46z4CmX6kw+HBUZZU++slOSyIuaJJJfOZ2mS2KvLXF/BMuoBLnQkhM1QGkalr/3Kga4RXiiHwahjv82o8KZnR3K/kw9p9vJO0zq4gE2yEYIDqC7RTJJ6XE843LLholFif3nhAIR5sR72eGYNooubeXIJbLm2uH/OPdMrDpEmg5z7YpTJvVQqjDNSrgBtdcafsujYDTWEBE2g7ydD1bJdMEtM1MgtKlhBhZQMvwLmID2COfMu6QJzPFaiONjIFoHjdWFOBsrJJoXiIv+w42Pw4BqfV1tJEknM/9+T1l8/vgzI4PnyF00bnnn2IVPJmvqFcjq2Z+N6ssO86CVff3Ajnh/ywSfI4qDOIFk4luM1WGafBz9OaNkxOzd8U07i37Jk5ChumjGLOdI1xBVLt1jQGfwqoyPcpJFRD5Ym5Uocz7iUSIc2mef2J95yIkeffOZpA+wslBTaOv4w/pu0BXBVkZSfjg38nqCyNUktlGWQz0vy0JjxIG42R8lQ8SG8XWsBDJpUHDmQsq9Dy7gxJMtiSCOLfdhCkAhKHPDytoACj/5cABquQrGAaGlrXFthqIXN3E+fK0UQrsn72j0AQ/FhJaBaHu4vg/l7JdKAkf//Qv8xiUG93zGTehybWckj1PV23r+3nMAoEVwf7S05/BpiygRkSHywAw527Axa6a0Es1qa9mPkPqc4f4JSMUW6zXeSl1t/ZeWeAdZMEtE0TgO+gz7cvXKGSH8yjqZauAKNtSCM1U87AOjxWW+YOn7EXefKYedpCuJu12lxehn6K7EKuF+s8hN4cANpKPTK7bW89biczItVQFcNRO39hjgwehzCm4FpBo4jDkTlFHERs+Fg0DFK27qJEt1v512FyR1rUiOMkcNQiG86xffRilSsMSXc3T0++jTsCJivrJg3N+nwdp3RuVunWDD/qkfbki386aA4mzOatdWeMTuVP/xiSCq2tPHrXIUdYyWjHeW8z/f+DlHr94M5447qELhafS7RNBHN0ZJoxmP066YuflOT02gW629rXw7tdhWh6l67icn5G6GL/vIZfZZQf/OgCKMoTrr+548WdJSl7wEMJ/PA6Ii0e1azAp7snHvGzqL3bKJ+PhLQkxR7161kWSHkbvG2pevgyCdN34ACKCJIb5NPM8LHAK+bLbJJp7ybBV7gaQ6qnGww6TuONiKVOBj5J8vuCLN9K54wFHt5rFTlYI+QBD30gbxLlQF/cKslFTzZbWpayAfMRgMXjH7kyaYeuB2KuUAYqfpwOli+xrycojkch04dbUOkvqj7b4ILDxXa4zaRXy0Umt3sJ8PspYQ447K8c84+5bnGbaB0+tbyxYbKo91SlAfPHtnWLSf9C14zHf7WQcj3Ew5t5gf9X9PAoaF042LcvZ73ncLD5HQG/Udi1YsJyl3XFeCqAmUFFuNjj9rxuSsgojcWxydSwOEa40QOv1G5Hm2Whv0AV/KaRgM2M+9SrtEe6vzL44+dreQyt309roY3Sahd4fvkkIqnaWB1ZjADOsLBJXI7ns1DOs61xJP9PFbLeWTwbs0YmwWMFA/FJW2xUjpGItSyhwgQx3ut+xFtwPMTEZWRgF5128RYRKyk/iTi6UK+8LLADncotzLexFQsAQQsA+IEfACycAaIk7bFRKgKXG3OuVvzdKYRU5tSCqQ/Qo2yK8xbJi6d3fw991RYl4D0/vMxJgohGT6MlHEKQEj99Sr8wd2kd0R5kC9MDNtGwMzoS8Yq4Qb2A8VlEqDoDHxhTAlRiW8cUTx5LgB5dfOwtaNp7Pp1o9fZPQzGzikhZjaUuI/Is6ew8bWSfVReNn+EniyDRUnzNvlEl0FU84B/zrwnYOK/JOSgD5NnACY/6wGQgMXdGXTgU+XM20B62lQvSM0ezpyZlC/O9m97NyQ0yUestwQy9yJCYOpL94LI/zO7OYnx/ydVu7UblAuogqdq2PC7VF9jaN+4ZlKY=,iv:NZ/jMMbf5aYEsyOUcMgsEIGZPaiBwD5NQaU00f5KmRM=,tag:F2efvUhdl4ibsZ0d7EO2IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMjI2R3JLbUdiam1XUXli
            dWJ6SE5Id1NyS2V2SVB3ZnI4WXdIRFQ3U3dvCnB5WHI4ZWxYbENLZk1iNVdwdUt3
            Z0w1cDRJdVRjTXRMM2Vxbkw3bmlFaDQKLS0tIFhKeTFaajVrL3A3b2w0TW5pc2ZK
            MkNjNFdSdTdqOWJGWmIwTjdhSHhBUk0K44nBAARCn8fQGOfhoNK6vV+mu+z41LWX
            6RAqPedW7py2XO9PfyffX69rmhtQAS9XDNSIKkHYn9u0j/+gwfOoiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T19:02:46Z"
    mac: ENC[AES256_GCM,data:nxxzvJcjvXA6Fk43CkLwTAkp5aDR4hMpMlC5vaAAFVZcOpwNHw8cN0jz7RuOXvir2ahPCFIoSLmp5SDgJsQ3f0aig9z1JMAAmPJMPMknfIHr7kt5ecikSsJV0gCzhpJfLacFH7PhfpNXA5NFcPqz+Nl6lC/yrShW1Lt266wlsgQ=,iv:2HJWjv5TH1gmuAg8KC7mQzvJUNQPBFn4Wdh603N6STg=,tag:kpWZPNg/3AgTel3w1ii+Bw==,type:str]
    pgp:
        - created_at: "2026-10-04T19:02:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAZAtQY0GM9CzhLU/HRU3vRyb8KpeiIzClrABtWm9A+WAw
            7vKxDZehKJMwWKD+LTSuueNjXmiQfVYGgntmM6B4WzYSN9QU0V7grgFoCPyRuNLb
            0l4BMtbQKlm5lrwc9wJRUyUuupzq1BjpKVCqkSYdp25lBcjLW5vbG4gvGWArEcVo
            qupNxF/EUlTzapydljOKdYh5z/i3a4IKuWli00CQrzxAwDqmo2Hbwga5UOWd4muo
            =v68C
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.3
