apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-config
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:9tbEHKA3FvHydYcMSkSRVc+chBXkuVXf6mwCkJUQhiBWP37y5SSMVYkPwSxWdKq03fm93bE4cUJF0NtBub8sUfB2eG7wZ4AcDeAh3BtBtFrM2LZ6U9D6FeBXFGHBRDjETGj+E1NBA0NWIoViEclpxthpKKySfPNReVGXDviSdu4ocQP8zpJTKrQGmhypkYST1cQlKtSSEJLh/8dyih+t63jvnUjLcv3MPZbz3ywXwqqKbyU51BFBaAFbS0hP13zuRIYi4v0OXlvlf0xnE/D/Vts2fpfGulOuZcjLNKdVDHlqZkxSfjtyClO4easQ81xcuksvGnYWkI1LAQ2CCLv1eRcGzObK2RtHw3M3gVDO9evDQpbj7FstW3asMQKjnTYx+C0i7WBlSOyva3h5hpjkz64H+z9fUEnTIQqcPi4FX6gDaL3InqgBDJ3xLINFecR3ydvwKtg2ltBeApW/auGQVMSFR0KwHXh7+9dyVVhKpKhgxEiiMuEmJHEMXmwc5dGK3YbYejDPJ0Trsxzaucn/wLbb8HzskAY5wcTGwDnx5g+bvWn70hYghItVH2Z2fmpfsvxALV60ZU7lugPLQ9Y4w+Pm99DLTDWJKHhg8kuxZk4OKmmTAQGM++VgAtmAS6D42Ku/aMe/JtUu7tV1DY8A8qe2QUWLQk3lc1YwBeN0Xm3t82pcdcjIBACI4L9JwN+TOKEJgJDW5FkYdU7b3pDB/DdOXa9eaRJ+q6NNh3UJtk2vZiwveSwzTUCiFkdOHOr1ji0pJc+fZyL79VpZHxzShdj+vs13dEUSR7ohAufawRHNLzJ38LgLtVwX3LnJwUinIxPOIUebifCcz8Gc1IWn/naD+MkoasNRaa1u+igbD3kVyKdX4+XFCaj5RosypNRs8gXC/YNb73dz6kX0R9Pn3nnRkIh/kVB7bEZc7JFPGfL8eBmTgt1tNSkbVKifm6LWZFTQAzHcJGYxJWTtchJKtEHlwu5g6h/Ji41T+Q9TQH1iQiqHVXs4rThv8IiM8GX8YpgB/8TYaN0ldA/WzD+WLk2Eo1rH8XZnSdBZtgg5W3GgNYphyoz2ULyYhH1cYH0LVhXjvOwrzjrUcK/zUT7Yzsw0YfpYSLUmNnjw3i526w6BiTNCRt3uTpBZrxU+v6cjc/WDhIi02O6pMhrbZymo5CAClKCe8QUPLWxcNZI8LlVOiGQX8I9CwKkeeZbOOSwmOXCIxp+8RtDfQiEgW6w66yH78q3pVCLp5/JZ42SLuZoPAf3rgeqlRcOdu9YjhQrnBgWmIG2tdL7N//qCFZp1FBGtcjTuwTnXl7BxM23O/P9FYoeyVh0yxZDWR4Ma0f4kz9tax2OftnA4jWGphqju2Jhcq303MfbyunZQUEjiBiJbloJ85uQvR2eIgabNAoe1v9wxkE4HvL6gNG4fmVP29ClVVB8qa0tZ38UaosSZnIpByALq+iwmglQrSAb4DCjkDpPSDofKtBWnMm6psAnNXzORvPk/Rs6+aC51OlPp6x8S/1V4CKzosWZ42fe6OUYpsFmWAnnzoS40UqV9gR7s2pu6RU46T/sG0CGcq8BYVYQzSWeAvTIcxSxqLUoze5gw7FZUDAanVc2K+jkwHHOWoVBItJYcsJRWiMzOthWya/y26q3xPmWlqmGobjvz6NnjXW9Sd075xwR3oPHI0UoEVWEzLjiZ7pz8y31nV+kPTlyz10j3lX8o/Flxtg4T4j8NeTpqILaFog/dls+ejl9AtgIyfLMH9/ZBL9HhwixYWxK7RKptwod5my+JPPUew7o7r+B/K181gRr1OWsnzp4ke/XG9sDmSdQIjaZn8PuOmo5BH7pWHx0AjjxFKTdH6L9Vk8xv1pKbXsbzSl5rnrFjjv8Zt5W1DZ0+LlWKZlSzxOCiIbp/TnLOUlaCc0mzdi4G,iv:ac/0v4NRy7f0mZpIe8Q/mCQBqkMWbdG4gGXOz1hZvHo=,tag:8Mbhphjr2WcHr/a3VI83Zw==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZDg2Y2ZFMGRzSzlmNXFR
            dSs5YnJZQ1JuVjdQYTRBaEZNTVhVMHEvOWdnClJwRWpZNUVwV0VaWE02TnpoTGth
            WFFPTm10TnVSV084ODRRSmNNeTR4VlUKLS0tIEFWa3RZd2FaYWlpVVFMbDhEZVkz
            YWJZUW1CcjRCYWM0TlZEM3JtdGNaM1kKpYs08JTkJ8YOxllIVzS1r1CbWXagkL+I
            VVblCu/A5zy/X4AsqqSt/XcpB9MBj2dx3FqufIRQ6BIcF06YE2e/Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T16:06:59Z"
    mac: ENC[AES256_GCM,data:2qNkxBQH3nvswSgFcGn84NAUa9MDU31DkuNBPXOFM2ptYpL0tfWgpaClUs8kjIPU1DCViliLyl7tl9bUgLVm96dPvEh1TpIFq/cCUnVDANC0Me/qnL92aoR8exVWCTkcaRfD/HPHyAWZN/lQdvNQx0bQmZqhdDZIuqHY6sBHg4c=,iv:OTGUz5F8Sc9zPhIillbyrHMx7Ee60xwsKoc7cxw6CuA=,tag:g+ViBAGc14/YnWmkW3i1wA==,type:str]
    pgp:
        - created_at: "2026-04-12T16:06:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA/bGl6EG+MtH4vYIkKg2D+fRdIwD4YnrO7azP/GtVQXQw
            RknPJh1XbhJKQ/4KEUpDwT7fSoLBydvG+owxlkKsEVIUGKEP/XXtm1sZ91N7mYhO
            0l4BFqCu7hnrXu1Xf6xtoaTnAaNRBsvyh58lhnOwaYnygy9PEQ6O8sXbUnzu40AQ
            5+Jm8+mgbvSZRPoScYSC1mYmDQxg2lQH109YA/tMgcBxGZzzlPwjvH+Xq2C5t1Xr
            =3yYZ
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
