apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-config
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:Lz+wX7lXsXC5ANEFtcz1I5zT6SEDCS0nubjKLhjKsrcB36md2UcMPyOIZYvWf/nLVl5a9CixZW2rnq25hHxQ+fdT8qwkNynnrdhGxAgEdEtAZC9F1zR2anYBWFL9Xp4aUzxzel83852xxWDYZfkvKyAQHOgeQeujKBqD0oX4V56LRBVoAF5HGKSw5vNpIanAwuvM69s9XyQFa7mx9/S+FpLIN96/UPUjMVkbcdVFaAUEImGplOnfw24RbT5D6xPc+WkKyHj9UDt0XN/MLmIyG4aF7m5hC/YQv29DF29gl0ZwTeP5m6cCKRo4aUZmOxjUEdeIifdUOyN5aY5ApsSVZ+qQJheK1QZhw++d6hIXPsJh1/WVNJdJutW2bPhLHYebm0y0tFsdjI+KUip5qgiP1O3RtcXuB0ODWhGOm2imt0sacSPTzYzjTck7MRRx3RPXcDb6Je6D6Ay3HsB6XlHaee6DxZaSPFVj1DmCtMaymzfnjs+ReVRAsWKevtBbLCW8DAFc2aXEqsPgqxvbexJoqQGOqtGWBVvHHt/ZnjRFyMftpRCPC1MZv2byDRN48Xne045/wONfk+aHPzmLXXTE3HYNIucdjPqQpEgMF5MTr3ikrIuT8RwaslMIFjRACp440DP+1GxU2cSE/AjghYrqUVmCYaqJXZCVg7MYCvFYtlviOiK4maR1CnhX7wDNTYZBPnfg9KA1EYpfDavbnDs1if8lrTJ9eSbeZfpz0uVcA0CD7YD1NsDVAFJtrw+801h6wDkUibtXdykKYwMVw+iKRlK45RdW/7v5flSJ5ltyo401+oS5lDXsc3iZ3sudkn+IUWMNPYZtDFhUnWJ9HhQeQGNW6NdSC6dNVS37zQXlx6eg9kDJR47XS6x/T5et3o/wxrvyGJv9WDI61f/a64R7GkSdbsE8zjdk7MJAsGt3Yr0ailOSA5QfrgQ/jK8EMKGLdxsNhP3ibG3yUG+NeaUNQwfnnmKCJnRSXdyMwUIazGrLeAOS+KWcuDlBw9C51cq5eU6A3859mls3YipbI8EXrYdjYZWbIOJfKuvtiPuTWpcFnQInyTJL6XeHNs+gGYzaSfFSR2FFdA8bKE7qnBwkApZyqNi2gfERuRRDh7ClTKV9k1o7X6DYIn7xXeoV6wOKdXQ4qDUZ99nPQAEER/KEjNpKXMRxZ7x+FZnoUL60pVeg2gab23mD71SqtbrpYm/cSfnuj9UmlgWpgvDCFuL+BcHK5Q4fxCemO7AQD/WlRSyuCKI+hvtOGc4DPJEaqIN1p5MlxyA7IGeU5xCl4bCnjcR6JXPNzCAYT+NtJdJuL+aMV2gi2phoDWg/4e6kofvrTfW3k7eS/TazAunLHN95VDXGAIb8npFcfJqKVvO50vyVLYjmO5OBba8YBjsLPVVPuTv3R/48PaN+1GvYSyIzw8GKrnRpBXdRadbA+IWnumcn5eoydtW7UlRUOa17CVyH7lnMtzrj3hKEa7J5IZaHm+ieRizU+uUGUeeLWYtxna4vq6Llqg4rwjsN4OZuChE4vV+ER8I5iVv0U/qqoag7+QUh2V62J/iq6r1meEuE52JzzA3ecG+HX3y+J+lHrok6iLmRyjVjP/7nGUprnqVZkohLtC/5fT7uMjuuWLIlcSWQZNyhnVl3NJLuCnMEe5Ivfh6yc1nQIj6ToxdVeYW4JAlcNbapG3K7gIK5FyZAnduoKNineg+PKRhgo9DuKANz9gDdqXooJCDuL1nzK45jEw2yyqoKIeNozG9YnwMjXY+PTrgwZdgbFCDqoqUDc5ptyKk89OTGJM1Ka+QiZIxCknHNSxRGp83tnhIegZJea8OSBKlTcknUgIQB5Um3G+yQgAlH99DuRQPLZjQOkHREvHtTNF5pmaolq8TqFTrKifQ9Js6eXwR5056gyldDiI/VHq91xoAQ0kFFzCkFcUNgNrk0OJ+g7FJqh4FNnSniTomoQizqTGU=,iv:JNz9lOMMB2whxN0NbWiYryLWZ7O0BKmGtOVzHu2D6ZQ=,tag:HnaPdauYOk9iyhiGLlcgnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa1UzeC9NaFkvNXFiNG1m
            ZnVTcjlqYjYyck1zSmI3WjdYZHVFaDlqQVhFClRxbk9sN0FjMmtPMk0rT3pKazk5
            UEFSdWFHMnM0bk5saENNTkhQSEt3LzAKLS0tIHhDOGxMeW42bmZ2WTBZV0pvdVht
            Q3BreTlHaTc5TXAzeEErVVdKc1d6UVkKrQ3YhvYR0OaF7boZS2kFit/7+S6cqr8n
            Oj0dOGVC+DrjGROq3EKmVIKui+OjlxzjEVmz7TkngBYH7hc9iwF3gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T03:46:56Z"
    mac: ENC[AES256_GCM,data:7hBknhsxZOgaNcne74F5UtLVxcVruaSOB3EaKQHo2s5eoAlLh19t8BMu0BTOI7GdwU4OlX47btAjMy9ySH9PgkZQzYA8pC4JR816aOZDS/zfAH/OWgGHZM3PVENiI8ozC462YmtTQ6AMDOZL9e2maEbn6CilHMO2uKtPKqZiR0M=,iv:ZWpzFuPlBLIUeUAvCf9wxWw7Rn79WCT5tRU+fll2KFo=,tag:uKkHV0RmB9EnAIvPp0dmiA==,type:str]
    pgp:
        - created_at: "2026-07-05T03:46:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA5yYOFV755dKRaK43bpazaFhQmhOOeA9jl9IP287VsCEw
            KbfFMDGLa6VM/AMW/6K5DxaMwqI9maatU1slQGZGxVcVvg+aRnCU6qMR0/4GBehE
            0lwBA3ciWMTUOX2mcu36B/iCvvxFOqJocNZl4OhQ/rTsw1yx+U0fDhVvdU684flT
            U5L74TfL7vTcri331L8vua/j17/tcOH0KiPT8jX1m4lHYVDH9pCtT0koR0hScA==
            =ey0p
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
