apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sponsors-bot-postgres
  namespace: apps
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 4Gi
    storageClass: "longhorn-strict-local"

  bootstrap:
    initdb:
      database: sponsors
      owner: sponsorbot_user
      secret:
        name: sponsors-bot-postgres-credentials
