apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-postgres-credentials
    namespace: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fxwcZO0Oe+52cQP7YbR2,iv:CsQsUkymbIZslx5CkDagCl2wq4mhlTIEWAbN/rRryOE=,tag:XL27QCQ4KkTRupt2bl62TQ==,type:str]
    password: ENC[AES256_GCM,data:n517t5a8qpmNjmm1Duw8kjvvpKo=,iv:/67hiYHMQCgs2lr/6Emz3WwoYKAxdZEKlZcmKEkP7r4=,tag:tMLvcs12mOkoEjxLrS58RA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidllJQm9KTEhOaHlXMlg5
            S0ptUGhJMTNUcUJYQkFKWG12MlNuMDNKdmdrCmhjTW9HVmkvaFp6MUdkdmpMU0NJ
            V1FkNEgwNFlCak9KU29zMDFNekovRzQKLS0tIE1sTi8rZGEzUVE2TDROeVl1bCt0
            eWVGL0F0c3dPcjEwVXF0ZXVJMjF2SG8Kh4HYb1jcCv5AUL58iN79B7Eqa9FDUaqS
            YDRp35sXjKrCVF5tAfHNX+gO6adN7qSBpkF6pcGO9974wu/Kyabv2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T03:47:02Z"
    mac: ENC[AES256_GCM,data:fkfIgHt7yOGey+jH4X8O0ti0PFANTbnE5xEizCl8NrPmjEOkIB/Kiuumr+yxnLT0+c3W7f/w8smdN7UpPNortXH7RYZDWDC8Tlh/6nmOd5RsiP6oEHYqEe01zugrbIgCBr4tupHOCoei7IoUPA+u0aRbqIDdhJBhhHH2BE7DAzk=,iv:z4mUrcdlOR3WLcnVger74MxSanJjWIqH1uoX/0Rkv8c=,tag:LVMnHe49PephDAAPoeFWJA==,type:str]
    pgp:
        - created_at: "2026-07-05T03:47:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAsE55M3mANNTEEfKSq0zPylPujy9zRJEqcSTvd9gDYXIw
            i3bHJ2qT2zrUrP687Hgs7EwYZgEFXGDDaaEwqnJ9tB+FpIX7eYdRoYh+r01BXsnQ
            0l4BzSHWFX5IByCvqSdfNl5p6BdCcYouuyBg720Tp/lc7lHZm/JIxcMGtaPX4kvW
            4wGk6UPqjk6k06kFKbNOhbIadAIC77ZqCNDHlr4IKj86UzftQij/hiDUWbcduY4i
            =AX8/
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
