apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-postgres-credentials
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:q7rTQFP1699E6T5jC3qm,iv:tsu7rfo4PL4bPVIAj6kb8JY5ruoYAjG4x5ZhPGzDnek=,tag:KyGb4+EapYt+onhcOSdrMg==,type:str]
    password: ENC[AES256_GCM,data:ToTUpUtryS/WWnCI5/jj+uKSA/A=,iv:S8l2NlR/ytj9wAqfjt5mt7bAGgZbmT4H+cELnbbM/5s=,tag:M/n2g3JleQQHVCCXJO8ADw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dVptT0JRN2c3NmY5QlVY
            a1BpS3YvaWE4WTFvME96Vm9OeVJSK2V5M3k0ClRqK1ZRS0JzcDdnWS9YeG42VHJN
            UklZV1NOSW9JVVhWNmQ5OWtZT2VVMVkKLS0tIHJIRDQwWnFpYlVJMys4QkxyS2hj
            ZzhRV3VzanhOVEIraGFnL01SNGtQaEkK5H26HLLCJZgK3d8LYZeenfLMKJDZIKfh
            /BgUwj/KUzh1rBzGmx/UVniCTN7FkRc/EmAfuNq+dnc/BWum5n47LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T04:08:26Z"
    mac: ENC[AES256_GCM,data:RjLJjD4ql7kXQmG1QBnOjxCSCUQLGDJK65SiMGQ8qrHHZ0FBQ8bbVVyh0nEagBurrK18WlUFmjv+lnXnK2JcqwAvenBQdRdNZAvI6JoxPl/uYSoKR4IGSms2GN46grmGJRdCteS9cl3nG+NEYBcIWTI+K/xUD7wRQV9+s1JoF+U=,iv:ETb2JB4IxMy3GMV3HgN2puqK06ZS8OlNs7z9uwh0LPw=,tag:yR7JG+WWTzNtoen3TMNYPA==,type:str]
    pgp:
        - created_at: "2026-07-05T04:08:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAgmBrnVCJhS9485mEHol3WF0BiOZYD0RjuqeTQ+iIC2Qw
            bmUsjzWZ3MNuJ/e+PetGTiv/zHqrGFAY98K42T8z3nuq5TdqzZA/W4qe1CpqHa01
            0lwBl0A7+qm+jsKDXrJrxjwSDbCUseAryCOqc6QrnYMOmHB/budTY5I2gdiHpgUI
            4hh1N3KfTzrKORVBRnn/bQ0DqWDM9MCJpt7tCgnZbcYEAE4WPMc1n9p9RFxq7A==
            =lBP4
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    version: 3.13.0
