apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sponsors-bot
  namespace: apps
spec:
  serviceName: sponsors-bot
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sponsors-bot
  template:
    metadata:
      labels:
        app: sponsors-bot
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: sponsors-bot-worker
          image: ghcr.io/nelsondane/sponsors-bot:latest@sha256:e933b7b9d2c4b852fc304826176de88835463e07e5d202e306c6c26a2716f845
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "main"]
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "main"]
        - name: sponsors-bot-web
          image: ghcr.io/nelsondane/sponsors-bot-web:latest@sha256:5df27965c8ba8d16be3e1e065bd43a62c1ae9b32a5e44b4afdd8937bf3029e61
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "web"]
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "web"]
        - name: cloudflare
          image: cloudflare/cloudflared:latest@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
          command:
            [
              "cloudflared",
              "tunnel",
              "--no-autoupdate",
              "--loglevel",
              "info",
              "--metrics",
              "0.0.0.0:2000",
              "run",
            ]
          envFrom:
            - configMapRef:
                name: sponsors-bot-tunnel
          ports:
            - containerPort: 2000
              name: metrics
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: config
          secret:
            secretName: sponsors-bot-config
        - name: tunnel
          configMap:
            name: sponsors-bot-tunnel
